### ISSUE TITLE
Doesn't work for me unfortunately :-(

### ISSUE THREAD

**Issue by rgpublic** [Moon-0xff/gnome-mpris-label#106]
There is "something" invisible right next to the clock. I can hover over it and I see a gray rectangle with rounded corners. I can click and I see the menu. I can open the settings etc. With a middle click I can pause/start the playback. But I don't see *anything* at all. No song title, no controls. Nothing. I wonder how I could possible debug this. I'm no Manjaro Linux, Gnome 46 and I've just enabled the extension via extensions.gnome.org.

**Comment by Moon-0xff** [comment]
Hello @rgpublic

What media player are you using?

**Comment by rgpublic** [comment]
@Moon-0xff : VLC

**Comment by Moon-0xff** [comment]
We found [this bug on VLC](https://github.com/Moon-0xff/gnome-mpris-label/issues/42#issuecomment-1589170272) that makes it omit metadata.

Maybe try pressing the stop button once, then resume playback, or turn off the `Hide when paused` setting in our extension.

It seems that the [MPRIS interface on VLC is shaky](https://code.videolan.org/videolan/vlc/-/issues/?search=mpris), you can raise an issue there if you want it fixed. Otherwise, hmm, maybe change of media player? Of course that's your choice, but **Video**LAN media player is aimed more to play **Videos** than music. Just a thought.

**Comment by Batwam** [comment]
I'd also try skip to the next song. For some reason the first songs doesn't trigger the mpris signal.

**Comment by rgpublic** [comment]
@Moon-0xff , @Batwam : You were right. Sometimes a little bit of creative thinking is actually the best solution. I just couldn't get the extension to work with VLC even with the changed settings, skipping etc. you mentioned etc.  I've now switched to Shortwave to listen to my radio stations. Much more convenient, much better interface. And this extension here just works out of the box now. Why haven't I thought of this before?  Facepalm. Thank you both!
