### ISSUE TITLE
Mouse can't use the volume controls

### ISSUE THREAD

**Issue by alexou2** [Moon-0xff/gnome-mpris-label#51]
in the menu, I can't configure an action for when I scroll. the default is to change the volume, buut it doesn't work and I can't configure any action for it.

**Comment by Batwam** [comment]
Hi, these options are currently disabled as the other actions wouldn't be something you'd want to use scroll for since scroll sends multiple requests so selecting something like "next song" would skip 5-10 songs at a time.
https://github.com/Moon-0xff/gnome-mpris-label/blob/main/prefs.js#L208

What you can do is change the "type" of volume you change though between system and app. 
![image](https://user-images.githubusercontent.com/56710655/236652908-964cb87d-b4d5-4663-a494-063d53c264ae.png)
You mention that this isn't working for you? The `application` mode could fail if this isn't implemented properly in the app you use:
- which app are you using?
- does the `global` mode work?

**Comment by alexou2** [comment]
The issue appears both in global mode and in app mode. Also, i can change the volume if i configure another button to do so, just not the scroll wheel. I only get the issue when i'm using a mouse.

**Comment by Batwam** [comment]
Ok, seems like a mouse issue with the event not being recognised then.

In relation to the greyed out drop downs, I just noticed that @Moon-0xff is already working on it in #50.

To troubleshoot the mouse issue, could generate a log from extensions.js to provide the number associated with the scroll for your mouse?

**Comment by Moon-0xff** [comment]
@Batwam already answered, as an addition you could check out my comments on #49

Regarding the problems with the scroll it looks like a detection issue (as @Batwam pointed out).
  
**Can you change the volume by scrolling on the volume icon?**  
If not then this might be a shell issue.

**Comment by alexou2** [comment]
If you mean the volume icon in the gnome status bar, yes. I can scroll over the icon and the volume will change. I am running ununto 22.04 with wayland if it can be helpful

**Comment by alexou2** [comment]
As far as i can tell, the problem is that the extension doesn't register scroll actions

**Comment by Moon-0xff** [comment]
Yes, that means the problem is our detection code, adding the line:
```js
log(delta)
```
just below the line:
```js
delta = Math.clamp(-1,delta,1);
```
and checking the output with `journalctl --follow` might be enough information to work out what's wrong with the extension.

**Comment by alexou2** [comment]
In which file?

**Comment by Moon-0xff** [comment]
`extension.js`, line 154 (current main).  
You need to reinstall the files with `./install.sh` if you aren't editing the files directly, and reload the shell (on wayland you need to log out to reload the shell).

**Comment by Batwam** [comment]
Any update on this?

**Comment by alexou2** [comment]
sorry, I didn't have time to try

**Comment by Moon-0xff** [comment]
I will add that if the above log doesn't produce any output it might be that your device doesn't generate a `Clutter.ScrollDirection.SMOOTH` event.

Pointer devices can create three types of "direction" events.   
We [ignore the other two](https://github.com/Moon-0xff/gnome-mpris-label/pull/30/commits/cd1da34dde6e84550f2fd0723170f20992da65b5) because they were [problematic and (possibly) redundant](https://github.com/Moon-0xff/gnome-mpris-label/pull/30#issuecomment-1465188725).

**Comment by Batwam** [comment]
@alexou2 could you please advise? If would be great to understand at what step the code fails to recognise the mouse action.

**Comment by alexou2** [comment]
it woks when using xorg. I'll try using wayland

**Comment by alexou2** [comment]
I can't get any log from the extension I tried lg and journalctl --follow and couldn't get the logs (even with the trackpad, which does change the volume)

**Comment by Batwam** [comment]
if you include `log('Hello World');` within the `_refresh()` loop do you see it?

**Comment by alexou2** [comment]
I can't see the log. when if _refresh() supposed to be triggered?

**Comment by Moon-0xff** [comment]
> I can't see the log. when if _refresh() supposed to be triggered?

Every 300 milliseconds by default.

**Comment by alexou2** [comment]
Can you show me a screenshot of what is the log supposed to look like? I might be doing something wrong

**Comment by Moon-0xff** [comment]
> Can you show me a screenshot of what is the log supposed to look like?

I don't know how's that of any use.

>  I might be doing something wrong

Perhaps you didn't run the installation script: `sh install.sh`

**Comment by alexou2** [comment]
I am modifying the extenson files directly and then log out

**Comment by alexou2** [comment]
I upgraded my install to ubuntu 23.04 to fix other problems and now it works
