### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by Batwam** [Moon-0xff/gnome-mpris-label#6]
Hello, I would suggest to update the [installation instructions](https://github.com/Moon-0xff/gnome-mpris-label#manual-installation) to let people know about the new install.sh script. Great extension by the way! :-)

**Comment by Moon-0xff** [comment]
I don't feel comfortable guiding people towards the install script since it doesn't have a fail-safe against being executed outside the repo directory.

Also, the main repository is sometimes a few changes ahead of the [ego](https://extensions.gnome.org/) version. We probably want to guide people to install the latest version instead of the latest commit. This will require some changes to the git repository.

**Comment by Batwam** [comment]
yeah, a failsafe like this I guess #9 

I agree that you don't really want to have a development version on the front page. You should probably pull these latest changes into some sort of `testing` branch first.

**Comment by Moon-0xff** [comment]
I prefer the opposite of that. A `stable` or `latest-version` branch.
Having the `stable` branch as the main one will be annoying to us and future contributors.

**Comment by Moon-0xff** [comment]
#9 was merged. latest-version branch was created.
We only need to update the installation instructions now.

**Comment by Batwam** [comment]
I'd suggest something like this:
![image](https://user-images.githubusercontent.com/56710655/205342944-35e42067-5cab-4cc4-a6f4-c74f83fb241d.png)

**Comment by Moon-0xff** [comment]
#10 was merged
