### ISSUE TITLE
Removing compatibility with GNOME 3.3x

### ISSUE THREAD

**Issue by Moon-0xff** [Moon-0xff/gnome-mpris-label#62]
Yesterday Debian 12 was released.  
Debian 12 includes GNOME 43 while the previous version included 3.38.

I don't know any other distribution that still ships a version of GNOME lower than 40, so I'm thinking of removing 3.3x compatibility in the next month or two.

**Comment by Batwam** [comment]
Considering the small % of users, I agree that we shouldn't worry about dropping gnome 3.3x compatibility if needed. I personally have one laptop with Gnome 3.36 (due to kernel compatibility with Nvidia drivers...) but EGO would still let me download the latest compatible version for it, while proposing the latest versions for my main machine.

Are you thinking about updating pref.js based on libAdwaita?

**Comment by Moon-0xff** [comment]
The basic idea will be to drop GTK3 workarounds and start writing `prefs.js` based on GTK4 objects.

The target version will be 40, I think libAdwaita was introduced later.

**Comment by Batwam** [comment]
Ok, yeah, it looks like libadwaita came out with Gnome 42.

**Comment by abisammy** [comment]
Any updates on this?

**Comment by Moon-0xff** [comment]
I'm currently too busy to work on this project.

**Comment by Moon-0xff** [comment]
I'm not so busy now, the two months had passed, and I updated Debian.

Time to break compatibility!  
As @Batwam suggested I think it will be best to also ditch 40, 41 and 42. I ~~don't want~~ can't test the extension on them anyway and the differences between 43 and previous 4x versions aren't insignificant.

@michlampert contributed #73 and I want to add something else alongside it. The best candidate would be to update prefs to use GTK4 widgets.

PRs are welcomed.

**Comment by Moon-0xff** [comment]
A new version is out. And `metadata.json` only declares compatibility for GNOME 43 and 44.

**Comment by Batwam** [comment]
Looking good and modern on my end too 👍
