### ISSUE TITLE
Chromium workaround is weird

### ISSUE THREAD

**Issue by Moon-0xff** [Moon-0xff/gnome-mpris-label#8]
The last discussion of #5 was about the chromium workaround:

```js
	if(!matchedEntries.length === 0)
		return matchedEntries[0][0]

	if (suspectAppName == "chromium" && matchedEntries.length === 0)
		matchedEntries = Gio.DesktopAppInfo.search("google-chrome")
	
	if(matchedEntries.length === 0)
		return null
```

It works. But why? It doesn't make logical sense.
Also, it only works with google-chrome and other chromium-based browsers might need a workaround too.

**Comment by Batwam** [comment]
for info, I have tested Opera/Brave/Vivaldi in a VM. As expected, they all report as `chromnium` and won't load the icons but the following (snipets of) code work. `Brave` had to be capitalised to work for some reason. The problem is obviously that since it's not searching through running apps, it will pick up the icon from the first app which is installed, regardless of whether it's the correct one or not... which is why I have loaded them in order of popularity:
`matchedEntries = Gio.DesktopAppInfo.search("Opera")`
`matchedEntries = Gio.DesktopAppInfo.search("Brave")`
`matchedEntries = Gio.DesktopAppInfo.search("Vivaldi")`

if we could somehow find our the app hidden behind the mpris source or exclude non-running apps that would be a lot easier...

These were installed using debs (Opera/Vivaldi) when no flatpak was available. Brave was flatpak. I tried the snaps but for some reaons there is an issue with appArmor and they can't seem to be able to get access to mpris so the extension doesn't work for snap versions of these browsers (works for firefox though...).

**Comment by Batwam** [comment]
I notied when I was playing around with D-Feet that in the list of mpris sources, Chrome provides a cmd info which could be perhaps used to better identify the various chromium derivatives than the current hack if we can extract it?
![image](https://user-images.githubusercontent.com/56710655/217848386-64da32ec-6c2c-42d7-9a12-1834d8eb6b89.png)

**Comment by Batwam** [comment]
ok, I think that i found a way as I was going through the mpris properties and spec. While `DesktopEntry` is optional and seems to be unreliable, `Identity` is not. I have put this interface into the extension and reported both `DesktopEntry` (first) and `Identity` below, the chromium browsers can now be reliably segragated!!!!
![Screenshot from 2023-02-11 16-46-08](https://user-images.githubusercontent.com/56710655/218249214-205d14ae-9658-4fed-8890-f37a7a40330e.png)

**Comment by Moon-0xff** [comment]
#27(merged) uses `Identity` to get the icon of the player (among other things) and removes the necessity for a workaround, therefore this issue is resolved.
